Created CustomerServiceImpl and tests for him
Nikita-Exeption/ChikenBell pull request #8
Opened 2022-07-03 19:29 UTC by Nikita-Exeption

2022-07-07 16:34 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/CustomerService.java
> +    Customer create(String name, String phone);
We need only one "create" method.

2022-07-07 16:35 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/CustomerService.java
> +    Customer update(String id, String name, String phone);
We need only one "update" method

2022-07-07 16:35 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/CustomerService.java
> +
We also need "findByPhone" method.

2022-07-07 16:36 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/impl/CustomerServiceImpl.java
> +        return customers;
Should return unmodifiable copy, not original collection!

2022-07-07 16:40 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/impl/CustomerServiceImpl.java
> +        customers.add(customer);
At this point service must check, that customer's phone is unique.

2022-07-07 16:40 UTC, zxRasp commented on src/main/java/org/nikita/chiken_bell/core/service/impl/CustomerServiceImpl.java
> +        customer.setPhone(phone);
At this point service must check, that customer's phone is unique.

2022-07-07 16:42 UTC, zxRasp requested changes
Please fix issues.

2022-07-08 13:50 UTC, Nikita-Exeption commented on src/main/java/org/nikita/chiken_bell/core/service/CustomerService.java
> +    Customer update(String id, String name, String phone);
Which of them

2022-07-08 13:50 UTC, Nikita-Exeption commented on src/main/java/org/nikita/chiken_bell/core/service/CustomerService.java
> +    Customer create(String name, String phone);
Which of them

2022-07-08 14:18 UTC, Nikita-Exeption commented on src/main/java/org/nikita/chiken_bell/core/service/impl/CustomerServiceImpl.java
> +        customers.add(customer);
ok

2022-07-08 14:20 UTC, closed without merging